config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # get 'welcome/directHtml'
  get 'welcome/abcde'
  get 'welcome/notFound'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'welcome#index'

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        # get all articles from db. make that as an instance variable. then we can access that in our erb.
        @articles = Article.all

    end

    def new 
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(permit_params)
            redirect_to @article  # this will hit GET /articles/id 
        else
            render 'edit'
        end
    end

    def create
        @article = Article.new(permit_params)
        if @article.save
            redirect_to @article  # this will hit GET /articles/id 
        else
            render 'new'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    def show
        @article = Article.find(params[:id])
    end

    private
        def permit_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        # get article. and spawn comment by article. save comment. go back to show article page.
        # @article = Article.find(params[])
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(params.require(:comment).permit(:commenter, :body))
        @comment.save
        redirect_to @article
    end

    def destroy
        # Another way to write it.
        # @comment = Comment.find(params[:id])
        # @comment.destroy
        # redirect_to article_path(params[:article_id])

        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to @article
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def abcde
    render plain: "STEVE OK"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>
<%= link_to  "Back", articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<p>
    <%= link_to 'New article', new_article_path %>
</p>

<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th></th>
    </tr>

    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(:id => article.id) %></td>
        <td><%= link_to 'Edit', edit_article_path(:id => article.id)%></td>
        <td><%= link_to 'Delete', article_path(:id => article.id), 
                method: :delete,
                data: { confirm: 'Are you sure?' } %> </td>
    </tr>
    <% end %>
</table>

<p>
    <%= link_to "Back to welcome page", welcome_index_path %>
</p>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form'%>
<%= link_to  "Back", articles_path %>

app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>

<p>
    <strong>Text:</strong>
    <%= @article.text %>
</p>

<table>
    <tr>
        <th>Commenter</th>
        <th>Body</th>
        <th></th>
    </tr>

    <%= render @article.comments %>
</table>


<%# create a create-comment section here 
  scope: article_comment
  url: What is the best url for "create (POST)"? POST /articles/:id/comments
  label commenter
  text_filed commenter
  label comment body
  text_area comment body
  submit button
%>

<h2> Add a comment </h2>
<%= render 'comments/form'%>

<%= link_to  "Edit Article", edit_article_path(id:@article.id) %><br>
<%= link_to  "Back", articles_path %>

app/views/comments/_comment.html.erb
<tr>
    <td><%= comment.commenter %></td>
    <td><%= comment.body %></td>
    <td><%= link_to  "Delete", article_comment_path(@article, comment), method: :delete, data: {confirm: "Are you sure to delete this comment?"} %></td>
</tr>

app/views/comments/_form.html.erb
<%= form_with model: [@article, @article.comments.build], local: true do |f| %>
<p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
</p>
<p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/comments/index.html.erb
<h1>Comments List </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/directHtml.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', articles_path %>